config/routes.rb
Rails.application.routes.draw do
  resources:tweets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets=Tweet.all
  end
  def new
    @tweet=Tweet.new
  end
  def create
    @tweet=Tweet.new tweet_params
    @tweet.save
    redirect_to tweets_path
  end
  private
  def tweet_params
    params.require(:tweet).permit(:title, :content, :links)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Woodpecker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <p> 
      <%=link_to 'Look here', new_tweet_path%>
      <%=link_to 'So many tweets', tweets_path%>

     </p>
  </body>
</html>

app/views/tweets/index.html.erb
<h1><b> Banana Bread makes me happy </b></h1>
<%@tweets.each do |tweet1|%>
<p><%=tweet1.title%> <%=tweet1.content%> <%=tweet1.links%> </p>
<%end%>

app/views/tweets/new.html.erb
<h1><b> This is a new page </b></h1>
<%=form_for @tweet do |form|%>
<%=form.label :title%>
<%=form.text_field :title%>
<%=form.label :links%>
<%=form.text_area :links%>
<%=form.label :content%>
<%=form.text_area :content%>
<%=form.submit%>
<%end%>